# This ingress uses rewrite annotaions
# See: https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.controller.ingressClass }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Request-ID,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin"
  name: user-service
  namespace: social-network
spec:
  rules:
    - host: social.nielski.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: user-service
              servicePort: 8120
  tls:
  - hosts:
    - social.nielski.com
    secretName: social-nielski-com